common:
  # Topics
  pointCloudTopic:  "/os_cloud_node/points" #"/os_cloud_node/points" #"velodyne_points"    "points_raw"     rslidar_points      # Point cloud data
  imuTopic: "/os_cloud_node/imu" # "/imu_correct" #"/os_cloud_node/imu" #"imu_data" #"imu_raw"      # IMU data

feature_extract:
  # Frames
  lidarFrame: "base_link"

  # Sensor Settings
  sensor: ouster #velodyne                            # lidar sensor type, either 'velodyne' or 'ouster' 'robosense' 'livox'
  N_SCAN: 32                                  # number of lidar channel (i.e.,Velodyne/Ouster/Robosense: 16, 32, 64, 128,Livox Horizon:6)
  Horizon_SCAN: 1024                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048,Livox Horizon: 4000)
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.0                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0                       # default: 1000.0, maximum lidar range to be used
  feature_enabled: 0                          # default: 1. use feature or not
  pointFilterRate: 4                          # default:1

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  odometrySurfLeafSize: 0.5                     # default: 0.4 - outdoor, 0.2 - indoor  only use surf ds here

mapping:
  dense_map_enable: true
  max_iteration: 10
  filter_size_surf: 0.3
  filter_size_map: 0.3
  cube_side_length: 1000                    # default 1000.
  extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
  extrinsic_T: [0.0 ,0.0, 0.0]  # lidar to imu coor
  extrinsic_R: [ 1, 0, 0, 
                 0, 1, 0, 
                 0, 0, 1]
